apply plugin: 'com.android.application'

android {
    namespace 'com.curse.rat'
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.curse.rat"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
